CREATE SCHEMA IF NOT EXISTS musicos;
SET search_path TO musicos, public;

CREATE TABLE ValorA (
    A REAL PRIMARY KEY
);
CREATE TABLE ValorB (
    B REAL PRIMARY KEY
);
CREATE TABLE ValorC (
    C REAL PRIMARY KEY
);
INSERT INTO ValorA VALUES (40);
INSERT INTO ValorB VALUES (50);
INSERT INTO ValorC VALUES (60);
